name: Release project-links-plugin for-jetbrains

on:
  release:
    types: [created]

jobs:
  release-for-jetbrains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2

      - name: build and release
        env:
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: cd for-jetbrains && ./release.sh

      - name: commit and push new snapshot version
        env:
          CI_COMMIT_MESSAGE: new snapshot version for-jetbrains
          CI_COMMIT_AUTHOR: release-for-jetbrains
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "viqueen@users.noreply.github.com"
          git add for-jetbrains/gradle.properties
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

      - uses: actions/upload-artifact@v3
        with:
          name: plugin artifacts
          path: |
            for-jetbrains/build/libs/project-links-plugin-*.jar
            for-jetbrains/build/distributions/project-links-plugin-*.zip
